Fix -Wformat compiler warning
error: format specifies type 'int' but the argument has type 'ui::Dataspace' [-Werror,-Wformat]
   91 |     LOG_ALWAYS_FATAL("%s isTextureValid:%d dataspace:%d"
      |                                                      ~~
   92 |                      "\n\tGrBackendTexture: (%i x %i) hasMipmaps: %i isProtected: %i texType: %i"
   93 |                      "\n\t\tGrGLTextureInfo: success: %i fTarget: %u fFormat: %u colorType %i",
   94 |                      msg, tex.isValid(), dataspace, tex.width(), tex.height(), tex.hasMipmaps(),
      |                                          ^~~~~~~~~
      |                                          static_cast<int32_t>( )

Test: build with upstream Clang
Change-Id: I81868618064fbb189affb0f55c4e3ab94e78430b
Merged-In: I81868618064fbb189affb0f55c4e3ab94e78430b
(cherry picked from commit d90ebf37bac881823a701190afd871dbc7495624)